#!/bin/bash

> FileIv

for pid in $(ps -Ao pid | tail -n +2)
do
	ppid=$(grep -Esh "^PPid" "/proc/"$pid"/status" | awk '{print $2}')
	sum_exec_runtime=$(grep -Esh "sum_exec_runtime" "/proc/"$pid"/sched" | awk '{print $3}')
	nr_switches=$(grep -Esh "nr_switches" "/proc/"$pid"/sched" | awk '{print $3}')
	if [[  "$nr_switches" != "0" ]] && [[ "$nr_switches" != "" ]]
	then
		art=$(echo "$sum_exec_runtime $nr_switches" | awk '{print $1 / $2}')
	fi
	if [[ "$ppid" != "" ]]
	then
		echo "ProcessID = "$pid" : Parent_ProcessID = "$ppid" : Average_Running_Time = "$art"" >> FileIv
	fi
done
echo "$(cat FileIv | sort -n -k7)" > FileIv
