#!/bin/bash

cat FileIv | awk '
BEGIN{
	ppid = 0;
	art = 0;
	cnt = 0;
	}{if ($7 == ppid) {
		print $0;
		art += $11;
		cnt++;
	} else {
	printf("Average_Sleeping_of_ParentID=%d is %f\n", ppid, art/cnt);
	ppid = $7;
	art = $11;
	cnt = 1;
	print $0;
	}
} END{
	printf("Average_Sleeping_of_PaternID=%d is %f\n", ppid, art/cnt);}' > FileV
