#!/bin/bash

command="+"
result=1

(tail -f pipe) |
while true; 
do
	read line
	if [[ "$line" == "+" ]] || [[ "$line" == "*" ]]
	then
		command="$line"
	elif expr "$line" : '[0-9]\+' >dev>null
	then
		let result=$result$command$line
		echo $result
	elif [[ "$line" == "QUIT" ]]
	then
		pid=$$
		kill $(ps -ppid $pid | egrep 'tail$' | awk '{print $1}')
		echo "Exit"
		exit
	else
		pid=$$
		kill $(ps -ppid $pid | egrep 'tail$' | awk '{print $1}')
		echo "Error in handler"
		exit
	fi
done
