#!/bin/bash

echo $$ > .pid
type=""
result=1
usr1()
{
	type="+"
}
usr2()
{
	type="*"
}
sigterm()
{
	echo "Finish"
	exit
}
trap 'usr1' USR1
trap 'usr2' USR2
trap 'sigterm' SIGTERM
while true
do
	case $type in
		"+")
			let result=$result+2
			echo $result
		;;
		"*")
			let result=$result*2
			echo $result
		;;
	esac
	sleep 1
done
